apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: vs
  namespace: gloo-system
  labels:
    app: httpbin
spec:
  virtualHost:
    domains:
    - 'api.example.com'
    routes:
    - matchers:
      - prefix: /httpbin/
      routeAction:
        single:
          upstream:
            name: default-httpbin-8000
            namespace: gloo-system 
      options:
        prefixRewrite: /
    options:
      waf:
        customInterventionMessage: 'ModSecurity intervention! Custom message details here..'
        ruleSets:
        - ruleStr: |
            # disable ruleid 930100 - TP-414237 - Path Traversal Attack (/../)
            # Note the underscore in this configuration, which is a malformed WAF policy, resulting in bad config being served to Envoy.
            _
            SecRuleRemoveById 124234
            SecRuleRemoveById 228932
            SecRuleRemoveById 490101